const users = [
    {
      name: "Alice Johnson",
      profilePic: "https://img.daisyui.com/images/stock/photo-1534528741775-53994a69daeb.webp",
      email: "alice.johnson@example.com",
      role: ["manager", "admin"],
      projects: ["Project A", "Project B", "Project C"],
      status: "active",
    },
    {
      name: "Bob Smith",
      profilePic: "https://img.daisyui.com/images/stock/photo-1494790108377-be9c29b29330.webp",
      email: "bob.smith@example.com",
      role: ["contributor"],
      projects: ["Project D"],
      status: "active",
    },
    {
      name: "Catherine Lee",
      profilePic: "https://img.daisyui.com/images/stock/photo-1502767089025-6572583495b6.webp",
      email: "catherine.lee@example.com",
      role: ["admin"],
      projects: ["Project E", "Project F", "Project G", "Project H"],
      status: "inactive",
    },
    {
      name: "David Brown",
      profilePic: "https://img.daisyui.com/images/stock/photo-1525332540231-6a7d27e88cc5.webp",
      email: "david.brown@example.com",
      role: ["manager", "contributor"],
      projects: ["Project I", "Project J"],
      status: "active",
    },
    {
      name: "Ella Wilson",
      profilePic: "https://img.daisyui.com/images/stock/photo-1534528573215-7dc85a0f5fc4.webp",
      email: "ella.wilson@example.com",
      role: ["contributor", "admin"],
      projects: ["Project K"],
      status: "inactive",
    },
    {
      name: "Franklin Miller",
      profilePic: "https://img.daisyui.com/images/stock/photo-1544725176-7c40e5a9d3f6.webp",
      email: "franklin.miller@example.com",
      role: ["admin", "manager"],
      projects: ["Project L", "Project M"],
      status: "active",
    },
    
        {
          name: "Alice Johnson",
          profilePic: "https://img.daisyui.com/images/stock/photo-1534528741775-53994a69daeb.webp",
          email: "alice.johnson@example.com",
          role: ["manager", "admin"],
          projects: ["Project A", "Project B", "Project C"],
          status: "active",
        },
        {
          name: "Bob Smith",
          profilePic: "https://img.daisyui.com/images/stock/photo-1494790108377-be9c29b29330.webp",
          email: "bob.smith@example.com",
          role: ["contributor"],
          projects: ["Project D"],
          status: "active",
        },
        {
          name: "Catherine Lee",
          profilePic: "https://img.daisyui.com/images/stock/photo-1502767089025-6572583495b6.webp",
          email: "catherine.lee@example.com",
          role: ["admin"],
          projects: ["Project E", "Project F", "Project G", "Project H"],
          status: "inactive",
        },
        {
          name: "David Brown",
          profilePic: "https://img.daisyui.com/images/stock/photo-1525332540231-6a7d27e88cc5.webp",
          email: "david.brown@example.com",
          role: ["manager", "contributor"],
          projects: ["Project I", "Project J"],
          status: "active",
        },
        {
          name: "Ella Wilson",
          profilePic: "https://img.daisyui.com/images/stock/photo-1534528573215-7dc85a0f5fc4.webp",
          email: "ella.wilson@example.com",
          role: ["contributor", "admin"],
          projects: ["Project K"],
          status: "inactive",
        },
        {
          name: "Franklin Miller",
          profilePic: "https://img.daisyui.com/images/stock/photo-1544725176-7c40e5a9d3f6.webp",
          email: "franklin.miller@example.com",
          role: ["admin", "manager"],
          projects: ["Project L", "Project M"],
          status: "active",
        },
      ]
  ;

  export default users